  var CAT = [
    /* --- skins: ocho de la liga andina --- */
    { id: 'gallito', name: 'GALLITO DE LAS ROCAS', cat: 'skin',
      ve: 'El ave nacional: naranja encendido y con esa CRESTA en forma de disco que le tapa media cara, con el pico asomando por debajo. Ala y cola negras, ojo amarillo.',
      q: 'El baile de cortejo: da saltitos, chilla y levanta polvo.',
      muerte: 'Se le viene abajo la cresta —que era todo su orgullo— y el pájaro se apaga soltando plumas naranjas.' },
    { id: 'puma', name: 'PUMA DE PIEDRA', cat: 'skin',
      ve: 'Tallado, como los de Chavín: cara de felino en bloque de piedra, con los ojos cuadrados y hundidos, espirales grabadas y los colmillos arriba y abajo.',
      q: 'EL RUGIDO: salen ondas talladas del color del grabado.',
      muerte: 'Se raja por el medio y se parte en cuatro bloques que caen.' },
    { id: 'papa', name: 'PAPA', cat: 'skin',
      ve: 'La papa andina, con sus bultos y sus hoyitos. Nada de redonda: irregular, como las de verdad. Por arriba le salen los BROTES, que se mueven.',
      q: 'Le revientan los brotes y echa hojitas por todas partes.',
      muerte: 'Se pudre: le salen manchas negras, se arruga, se hunde y le rondan dos moscas.' },
    { id: 'aji', name: 'AJÍ', cat: 'skin',
      ve: 'Rocoto encendido: cuerpo rojo brillante con su rabito verde y sus hojas, cara de pillo y un hilito de humo que le sale siempre por arriba.',
      q: 'ECHA FUEGO por la boca, una llamarada que sale disparada.',
      muerte: 'Se consume: se le va el color, se arruga, se retuerce y queda un ají seco con las semillas fuera.' },
    { id: 'sapo', name: 'SAPO', cat: 'skin',
      ve: 'El sapo de bronce del juego de la cantina, sentado, con las patas apoyadas, los ojos saltones y la boca abierta de par en par esperando la moneda.',
      q: 'TRAGA la moneda y suena la campanilla.',
      muerte: 'Se le cae la moneda por dentro —suena— y el bronce se cubre de verdín hasta quedarse de adorno.' },
    { id: 'tumi', name: 'TUMI', cat: 'skin', cofre: true,
      ve: 'El cuchillo ceremonial de oro: arriba la figura del Naylamp con su abanico de rayos, los ojos alados y las turquesas; abajo, la media luna del filo, que es la boca.',
      q: 'EL DESTELLO: el oro suelta un fogonazo con sus rayos que ciega.',
      muerte: 'Se le desprende el filo, que cae clavándose, saltan las turquesas y la figurita se apaga detrás.' },
    { id: 'inti', name: 'INTI', cat: 'skin', cofre: true,
      ve: 'El sol con cara: disco de oro con los rayos alrededor —rectos y ondulados, alternando y girando despacio— y la cara grabada dentro.',
      q: 'EL MEDIODÍA: se pone blanco un instante y los rayos se estiran.',
      muerte: 'Un ECLIPSE: una sombra redonda le cruza por delante, se lo come entero, queda el anillo de fuego un momento y salen las estrellas.' },
    { id: 'nazca', name: 'COLIBRÍ DE NAZCA', cat: 'skin', cofre: true,
      ve: 'No es un pájaro: es el DIBUJO del pájaro. El geoglifo trazado con la línea clara sobre la tierra del desierto, con su surco y sus piedrecillas.',
      q: 'Se enciende el trazo entero, como visto desde el cielo, y levanta polvo.',
      muerte: 'El viento del desierto borra el trazo en diagonal y se lleva la tierra. No queda nada.',
      ojo: 'La única que no es una cosa ni un bicho: es una raya en el suelo.' },

    /* --- accesorios --- */
    { id: 'acc_montera', name: 'MONTERA', cat: 'accesorio',
      ve: 'El sombrero de ala ancha, con la copa y la cinta bordada de rombos.' },
    { id: 'acc_poncho', name: 'PONCHO', cat: 'accesorio',
      ve: 'La tela cayéndole por los hombros, con sus franjas y los flecos ondeando.' },
    { id: 'acc_quena', name: 'QUENA', cat: 'accesorio',
      ve: 'La flauta de caña pegada a la boca, con sus agujeros, soltando notas.' },
    { id: 'acc_orejeras', name: 'OREJERAS DE ORO', cat: 'accesorio',
      ve: 'Los discos de oro con turquesa de los señores mochica, meciéndose al correr.' },
    { id: 'acc_trenzas', name: 'TRENZAS', cat: 'accesorio',
      ve: 'Dos trenzas largas que se mecen, cada una con su pompón de lana de colores.' },
    { id: 'acc_oro', name: 'MÁSCARA DE ORO', cat: 'accesorio', cofre: true,
      ve: 'La máscara funeraria sicán, con los ojos alados, la nariz en relieve y el cinabrio rojo.' },
    { id: 'acc_plumas', name: 'PLUMAS DE GUACAMAYO', cat: 'accesorio', cofre: true,
      ve: 'Nueve plumas de colores abiertas hacia atrás, sujetas por una vincha.' },

    /* --- efectos --- */
    { id: 'efx_coca', name: 'HOJAS DE COCA', cat: 'efecto',
      ve: 'Van cayendo hojas verdes que giran y se posan por el camino.' },
    { id: 'efx_nieve', name: 'NIEVE', cat: 'efecto',
      ve: 'El granizo fino de la cordillera, cayéndole en diagonal por detrás.' },
    { id: 'efx_serpentina', name: 'SERPENTINA', cat: 'efecto',
      ve: 'Tres cintas de carnaval que se enroscan y se van soltando.' },
    { id: 'efx_tejido', name: 'TEJIDO', cat: 'efecto',
      ve: 'Por donde pasa deja una faja tejida con sus rombos y sus rayas.' },
    { id: 'efx_polvoro', name: 'POLVO DE ORO', cat: 'efecto', cofre: true,
      ve: 'La arenilla dorada del río, que brilla y se apaga a su paso.' },
    { id: 'efx_lineas', name: 'LÍNEAS DE NAZCA', cat: 'efecto', cofre: true,
      ve: 'El camino queda grabado en el suelo como un geoglifo: surco oscuro, línea clara y piedras al borde.' },

    /* --- emotes --- */
    { id: 'emo_achachau', name: 'ACHACHAU', cat: 'emote',
      ve: 'Muerto de frío: tiritando, morado, con los ojos apretados, la boca en zigzag y el vaho saliéndole.' },
    { id: 'emo_huayno', name: 'HUAYNO', cat: 'emote',
      ve: 'Bailando: se mece de lado con el sombrerito ladeado y le salen notas.' },
    { id: 'emo_chevere', name: 'CHÉVERE', cat: 'emote',
      ve: 'Un ojo guiñado, sonrisota de oreja a oreja y el pulgar arriba.' },
    { id: 'emo_chau', name: 'CHAU', cat: 'emote',
      ve: 'Diciendo adiós con la mano, meciéndola de lado a lado.' },
    { id: 'emo_rico', name: 'QUÉ RICO', cat: 'emote',
      ve: 'Relamiéndose: ojos entornados de gusto, la lengua fuera y los mofletes contentos.' }
  ];
