  var CAT = [
    /* --- skins: diez yōkai --- */
    { id: 'tengu', name: 'TENGU', cat: 'skin',
      ve: 'El duende de la montaña: cara roja con la NARIZ larguísima, cejas, barba y melena blancas, el tokin negro atado a la frente y un abanico de plumas en la mano.',
      q: 'EL ABANICAZO: barre el abanico por delante y suelta remolinos de viento.',
      muerte: 'Se lo lleva su propio torbellino: gira cada vez más deprisa, sube, se hace pequeño y deja plumas cayendo.' },
    { id: 'kappa', name: 'KAPPA', cat: 'skin',
      ve: 'El diablillo del río: pico amarillo, caparazón de tortuga a la espalda, flequillo de tazón y el PLATO de agua en la coronilla, con el agua meneándose al correr. La piel va del color del jugador tirando a verde.',
      q: 'Escupe un CHORRO de agua que cruza el pasillo y salpica al final.',
      muerte: 'Hace una reverencia, se le vacía el plato —sin agua pierde la fuerza, dice la leyenda— y cae de bruces.' },
    { id: 'tanuki', name: 'TANUKI', cat: 'skin',
      ve: 'El mapache-perro que cambia de forma: antifaz oscuro, hocico crema, orejas redondas, cola gorda a anillos y la HOJA en la cabeza con la que hace sus trucos.',
      q: '¡DORON!: puf de humo y se convierte en la tetera de hierro del cuento de Bunbuku, con su cabecita y su cola. Otro puf y vuelve.',
      muerte: 'Se le cae la hoja, puf de humo, y solo queda la hoja cayendo. Nunca hubo tanuki.' },
    { id: 'daruma', name: 'DARUMA', cat: 'skin',
      ve: 'El muñeco que no se cae: huevo lacado del color del jugador, cara blanca con cejas de grulla y bigote, 福 (suerte) en oro en la tripa y UN SOLO OJO pintado. Come cabeceando hacia delante.',
      q: 'Llega un pincel y le pinta el otro ojo: el deseo cumplido, con destellos dorados.',
      muerte: 'Le dan un golpe y se endereza; otro, y se endereza; al tercero se raja por la mitad y cada mitad cae por su lado.' },
    { id: 'kasa', name: 'KASA-OBAKE', cat: 'skin',
      ve: 'El paraguas viejo que cobra vida: papel encerado del color del jugador con un remiendo, un OJO enorme, la lengua fuera y una sola pierna peluda con su geta, a saltos. La tela se abre como una boca.',
      q: 'SE ABRE de golpe, girando, y se sacude el agua.',
      muerte: 'Una racha de viento le da la vuelta, como a los paraguas de verdad, y se lo lleva dando vueltas.' },
    { id: 'chochin', name: 'CHŌCHIN-OBAKE', cat: 'skin',
      ve: 'El farolillo de papel encantado: rojo con un toque del color del jugador, con el blasón de las tres comas, el gancho de colgar y un ojo. Se le raja el papel y esa raja es la boca: dentro se ve la vela.',
      q: 'LLAMARADA: echa fuego por la boca y el papel se enciende entero.',
      muerte: 'Se le apaga la vela, el papel se pliega como un acordeón y queda un hilo de humo.' },
    { id: 'namazu', name: 'NAMAZU', cat: 'skin',
      ve: 'El siluro gigante que provoca los terremotos: cabezota chata, bocaza, bigotes larguísimos que ondean y el cuerpo culebreando detrás.',
      q: 'TERREMOTO: tiembla todo y salen ondas de choque por el suelo.',
      muerte: 'Le cae encima la KANAME-ISHI, la piedra sagrada con su cuerda que lo tiene sujeto en la leyenda, y lo deja clavado.',
      ojo: 'Sustituye al RYŪ (dragón oriental) de la idea inicial: el juego ya tiene DRAGÓN.' },
    { id: 'kitsune', name: 'KITSUNE', cat: 'skin', cofre: true,
      ve: 'Zorra de CINCO COLAS en abanico, con la cara de las máscaras de Inari: hocico largo, blanco, rayas bermellón y ojo rasgado. Las puntas de las colas van del color del jugador y un fuego fatuo azul la sigue.',
      q: 'KITSUNEBI: un corro de fuegos azules que gira a su alrededor.',
      muerte: 'Se le apagan las colas una a una, cada una se va hecha fuego fatuo, y al final ella misma es una llama azul que se apaga.' },
    { id: 'oni', name: 'ONI', cat: 'skin', cofre: true,
      ve: 'El ogro: dos cuernos, melena negra encrespada, ojo amarillo saltón, colmillos y el KANABŌ, la maza de hierro con pinchos, al hombro. La cara es del color del jugador: oni rojo, azul, verde...',
      q: 'EL MAZAZO: la maza pasa por encima y golpea el suelo delante, con estallido y grietas.',
      muerte: 'El mamemaki del Setsubun: le llueven judías tostadas, da un respingo, suelta la maza y sale huyendo encogido.' },
    { id: 'maneki', name: 'MANEKI-NEKO', cat: 'skin', cofre: true,
      ve: 'El gato de la suerte, de porcelana: manchas del color del jugador, collar rojo con cascabel, el koban de oro abrazado y la otra pata LEVANTADA. Come saludando: cada bocado es un "ven, ven" con la pata.',
      q: 'LLUVIA DE KOBAN: agita la pata a toda prisa y salen monedas de oro por el aire.',
      muerte: 'Se tambalea, se hace añicos como la porcelana que es y el cascabel sale rodando.' },

    /* --- accesorios --- */
    { id: 'acc_kitsunemen', name: 'MÁSCARA KITSUNE', cat: 'accesorio',
      ve: 'La máscara de zorro de los festivales, blanca con los trazos bermellón, echada a un lado de la cabeza con su cordón.' },
    { id: 'acc_kasa', name: 'KASA DE PAJA', cat: 'accesorio',
      ve: 'El sombrero cónico de paja trenzada, ancho y un poco caído hacia delante.' },
    { id: 'acc_chonmage', name: 'CHONMAGE', cat: 'accesorio',
      ve: 'El peinado de samurái: coronilla afeitada, el pelo negro recogido detrás y el moño doblado encima, atado con cordón blanco.' },
    { id: 'acc_ramen', name: 'RAMEN', cat: 'accesorio',
      ve: 'Un cuenco de ramen humeante en la cabeza: cuenco rojo con greca, fideos, naruto, huevo, alga y los palillos clavados.' },
    { id: 'acc_katana', name: 'KATANA', cat: 'accesorio',
      ve: 'A la espalda, en su vaina lacada: asoman la empuñadura trenzada por encima del hombro y la contera por abajo, y la correa cruza el cuerpo.' },
    { id: 'acc_kabuto', name: 'KABUTO', cat: 'accesorio', cofre: true,
      ve: 'El casco de samurái: cuenco de hierro remachado, astas doradas, sol en el frente y el cubrenuca de láminas del color del jugador.' },
    { id: 'acc_raijin', name: 'TAMBORES DE RAIJIN', cat: 'accesorio', cofre: true,
      ve: 'El aro de tambores del dios del trueno girando alrededor, cada tambor con su tomoe; de vez en cuando salta un rayo de uno a otro.' },

    /* --- efectos --- */
    { id: 'efx_torii', name: 'TORII', cat: 'efecto',
      ve: 'Va dejando puertas de santuario bermellón por el camino, como el paseo de Fushimi Inari.' },
    { id: 'efx_olas', name: 'OLAS', cat: 'efecto',
      ve: 'La ola de Hokusai: se levanta detrás de él, se enrosca con sus garras de espuma y rompe.' },
    { id: 'efx_origami', name: 'ORIGAMI', cat: 'efecto',
      ve: 'Grullas de papel de su color que salen volando por detrás, batiendo las alas.' },
    { id: 'efx_farolillos', name: 'FAROLILLOS', cat: 'efecto',
      ve: 'Farolillos de papel encendidos que se quedan flotando y suben despacio.' },
    { id: 'efx_onibi', name: 'ONIBI', cat: 'efecto', cofre: true,
      ve: 'Fuegos fatuos azules que se quedan temblando donde pasó y se apagan.' },
    { id: 'efx_koi', name: 'KOI', cat: 'efecto', cofre: true,
      ve: 'Dos carpas koi le siguen nadando, una con las manchas de su color, y el agua se ondula a su paso.' },

    /* --- emotes --- */
    { id: 'emo_kawaii', name: 'KAWAII', cat: 'emote',
      ve: 'Ojazos brillantes, coloretes y boquita abierta, dando saltitos entre destellos.' },
    { id: 'emo_banzai', name: '¡BANZAI!', cat: 'emote',
      ve: 'Salta con los dos brazos arriba, ojos de alegría y la boca abierta de par en par.' },
    { id: 'emo_itadakimasu', name: 'ITADAKIMASU', cat: 'emote',
      ve: 'Unos palillos le acercan un nigiri de salmón, abre la boca, se lo zampa y mastica con los mofletes colorados.' },
    { id: 'emo_zen', name: 'ZEN', cat: 'emote',
      ve: 'Ojos cerrados, calma total, y el ensō —el círculo de pincel— trazándose solo detrás.' },
    { id: 'emo_ninja', name: 'NINJA', cat: 'emote',
      ve: 'Capucha oscura con la rendija de los ojos; cada poco, ¡puf!, desaparece en humo y vuelve.' }
  ];
