  var CAT = [
    /* --- skins: diez de mitología --- */
    { id: 'medusa', name: 'MEDUSA', cat: 'skin',
      ve: 'Cabeza de mujer con siete serpientes por pelo, cada una con su vida: se mecen, miran y sacan la lengua. Labios pintados, dos colmillos y el ojo con la pupila rajada.',
      q: 'LA MIRADA: un cono verde que sale del ojo y va dejando piedra por donde pasa.',
      muerte: 'Acaba petrificada ella misma: se vuelve gris, se queda tiesa, se agrieta y se cae a cascotes.' },
    { id: 'ciclope', name: 'CÍCLOPE', cat: 'skin',
      ve: 'Bruto de un solo OJO enorme que le ocupa media cara, con la ceja de una pieza, dos colmillos de abajo y tres mechones tiesos.',
      q: 'El PISOTÓN: se deja caer y levanta anillos de polvo alrededor.',
      muerte: 'Se le cierra el ojo despacio, da dos tumbos y se desploma de bruces levantando una polvareda.' },
    { id: 'golem', name: 'GOLEM', cat: 'skin',
      ve: 'Un pedrusco con cara: bloques mal encajados, grietas que laten por dentro y la RUNA de la frente, que es lo único que lo mantiene de pie.',
      q: 'Se endurece: la runa arde y le salen placas de piedra alrededor.',
      muerte: 'Se le apaga la runa y, sin nada que lo sujete, se desmorona en bloques que caen uno detrás de otro.' },
    { id: 'esfinge', name: 'ESFINGE', cat: 'skin',
      ve: 'Cara de piedra con el tocado a rayas de los faraones —las rayas van del color del jugador—, la barba postiza, el ojo pintado y una zarpa de león delante.',
      q: 'EL ACERTIJO: un interrogante de oro que sale flotando y se queda ahí, esperando respuesta.',
      muerte: 'Se deshace en arena de delante hacia atrás, y el viento se la lleva.' },
    { id: 'icaro', name: 'ÍCARO', cat: 'skin',
      ve: 'El chaval de las alas de cera: dos alas de plumas pegadas con pegotes de cera, cara de crío con los mofletes colorados y cero idea de lo que le espera.',
      q: 'SE ELEVA: las alas baten fuerte, sube y va soltando plumas.',
      muerte: 'El sol le derrite la cera, las plumas se sueltan una a una y cae dando vueltas.',
      ojo: 'La única skin que se muere por su propia Q.' },
    { id: 'fenix', name: 'FÉNIX', cat: 'skin', cofre: true,
      ve: 'Ave de brasa con cresta de llamas, cola de fuego que ondea detrás y pico de oro. El color del jugador le tiñe las plumas.',
      q: 'ARDE ENTERO: se pone incandescente y suelta brasas en todas direcciones.',
      muerte: 'Se quema hasta la ceniza, la ceniza brilla un instante —amaga con renacer— y se apaga. Es lo que lo hace fénix.' },
    { id: 'genio', name: 'GENIO', cat: 'skin', cofre: true,
      ve: 'De la lámpara: turbante con su joya y su plumita, barba en punta y, de cintura para abajo, una cola de humo que sale de la lámpara de oro.',
      q: 'Te concede el deseo: la lámpara suelta un chorro de destellos dorados.',
      muerte: 'Lo llama la lámpara: se estira, se hace humo y entra por la boca. La lámpara da un último destello y se queda ahí.' },
    { id: 'triton', name: 'TRITÓN', cat: 'skin', cofre: true,
      ve: 'Medio pez: escamas, aleta por oreja, cresta dorsal, barba de alga que ondea y una caracola que le hace de cuerno.',
      q: 'Sopla la caracola y salen tres olas rompiendo hacia delante.',
      muerte: 'Se queda sin agua: se seca, se le agrieta la piel y queda tieso, con un charquito debajo que se evapora.' },
    { id: 'parca', name: 'LA PARCA', cat: 'skin', temporada: true,
      ve: 'La capucha con NADA dentro salvo dos luces verdes flotando, y la guadaña asomando por detrás. El hueco de la capucha es la boca.',
      q: 'EL GUADAÑAZO: un arco blanco que cruza el pasillo de lado a lado.',
      muerte: 'La capucha se desinfla —dentro no había nadie—, las dos luces se apagan y la guadaña cae al suelo.',
      ojo: 'De temporada: solo sale en Halloween, como CALABAZA y NOCHE DE BRUJAS.' },
    { id: 'jinete', name: 'JINETE SIN CABEZA', cat: 'skin', temporada: true,
      ve: 'Del cuello para arriba no hay nada: solo el cuello de la capa, vacío, y encima la CALABAZA encendida que lleva por cabeza, con su vela dentro.',
      q: 'La lanza por delante, dejando estela de fuego.',
      muerte: 'La calabaza se le cae y se estrella en cascos, la vela se apaga y el cuello vacío se deshace en niebla.',
      ojo: 'De temporada: solo sale en Halloween.' },

    /* --- accesorios --- */
    { id: 'acc_carnero', name: 'CUERNOS DE CARNERO', cat: 'accesorio',
      ve: 'Los cuernos enroscados de Amón, uno a cada lado, con sus anillos marcados.' },
    { id: 'acc_zeus', name: 'BARBA DE ZEUS', cat: 'accesorio',
      ve: 'Barba blanca rizada con bigote, y un rayito que se le escapa por detrás.' },
    { id: 'acc_serpiente', name: 'SERPIENTE', cat: 'accesorio',
      ve: 'Enroscada al cuello, con la cabeza asomando por delante y la lengua fuera.' },
    { id: 'acc_venda', name: 'VENDA DEL ORÁCULO', cat: 'accesorio',
      ve: 'La tira que le tapa los ojos, con el nudo detrás, las puntas ondeando y un ojo pintado encima: el que de verdad ve.' },
    { id: 'acc_mascara', name: 'MÁSCARA DE TEATRO', cat: 'accesorio',
      ve: 'La máscara griega de la comedia, de yeso, sujeta por su palito.' },
    { id: 'acc_alado', name: 'CASCO ALADO', cat: 'accesorio', cofre: true,
      ve: 'El casquete de bronce de Hermes, con dos alitas que baten a los lados.' },
    { id: 'acc_ojo', name: 'OJO QUE TODO LO VE', cat: 'accesorio', cofre: true,
      ve: 'Un ojo flotando encima de la cabeza, con su resplandor, que mira adelante y atrás.' },

    /* --- efectos --- */
    { id: 'efx_rayos', name: 'RAYOS', cat: 'efecto',
      ve: 'Por donde pasa quedan rayos quebrados que chisporrotean y se apagan.' },
    { id: 'efx_arena', name: 'ARENA', cat: 'efecto',
      ve: 'Un reguero de arena que se va deshaciendo por el camino.' },
    { id: 'efx_runas', name: 'RUNAS', cat: 'efecto',
      ve: 'Deja símbolos encendidos de su color que laten y se van apagando.' },
    { id: 'efx_pisadas', name: 'PISADAS DE PIEDRA', cat: 'efecto',
      ve: 'Donde pisa queda una losa de piedra marcada, que dura un rato.' },
    { id: 'efx_brasas', name: 'BRASAS', cat: 'efecto', cofre: true,
      ve: 'Va dejando ascuas que respiran, se avivan y se apagan.' },
    { id: 'efx_niebla', name: 'NIEBLA', cat: 'efecto', cofre: true,
      ve: 'La bruma del inframundo, pegada al suelo, que se abre a su paso.' },

    /* --- emotes --- */
    { id: 'emo_oraculo', name: 'ORÁCULO', cat: 'emote',
      ve: 'Se le ponen los ojos en blanco y le sale un resplandor: está viendo lo que viene.' },
    { id: 'emo_petrificado', name: 'PETRIFICADO', cat: 'emote',
      ve: 'Se vuelve piedra gris, con las grietas y la cara de horror, y se le van cayendo cascotes.' },
    { id: 'emo_divino', name: 'DIVINO', cat: 'emote',
      ve: 'Aureola flotando, ojos cerrados de paz y una luz dorada por detrás.' },
    { id: 'emo_maldicion', name: 'MALDICIÓN', cat: 'emote',
      ve: 'Aura morada dando vueltas, ojos rojos encendidos y una sonrisa torcida.' },
    { id: 'emo_invocando', name: 'INVOCANDO', cat: 'emote',
      ve: 'Recitando, con los ojos encendidos y un círculo mágico girando debajo.' }
  ];
