  var CAT = [
    /* --- skins: ocho objetos --- */
    { id: 'discos', name: 'MÁQUINA DE DISCOS', cat: 'skin', cofre: true,
      ve: 'Una Wurlitzer de las de verdad: arco de neón del color del jugador que respira, ventana con el vinilo dando vueltas, rejilla de altavoz y la botonera de selección. La RANURA DE LOS DISCOS, abajo del todo, es la boca.',
      q: 'Sube el volumen: el disco se acelera, el neón se enciende del todo y salen ondas y notas que empujan hacia delante.',
      muerte: 'Chirría la aguja, se le va la luz y el vinilo sale rodando por la ranura mientras el mueble se vence.' },
    { id: 'tele', name: 'TELEVISOR', cat: 'skin', cofre: true,
      ve: 'Tele de tubo con antenas de conejo y la joroba asomando por detrás. La PANTALLA es la cara: dos ojos de fósforo verde, el barrido del tubo cruzando y la mitad de abajo que se abre para comer.',
      q: 'Cambia de canal de golpe: la imagen salta, revienta en estática y suelta un chispazo.',
      muerte: 'La imagen se cierra en una raya, luego en un punto, y el mueble se queda muerto echando humo.',
      ojo: 'El guiño está en que la cara no está pintada: es lo que están dando en la tele.' },
    { id: 'cabina', name: 'CABINA TELEFÓNICA', cat: 'skin', cofre: true,
      ve: 'La cabina de siempre, con el armazón del color del jugador: cristales en cuadrícula, el aparato colgado al fondo, el letrero encendido arriba. La PUERTA es la boca.',
      q: 'Un timbrazo que la hace temblar entera y sale en ondas.',
      muerte: 'Los cristales se rajan, estallan en trozos y el armazón se vence de lado.' },
    { id: 'camara', name: 'CÁMARA DE FOTOS', cat: 'skin',
      ve: 'Réflex de carrete con su banda de cuero: el OBJETIVO es el ojo, con el cristal azulado y su destello, el flash arriba y el disparador rojo. La tapa del carrete es la boca.',
      q: 'Flashazo: un fogonazo blanco con sus rayos que ciega todo lo que tiene delante.',
      muerte: 'Se le vela el carrete —un blanco que se la come— y queda desarmada, con la película saliéndosele.' },
    { id: 'reloj', name: 'DESPERTADOR', cat: 'skin',
      ve: 'El de dos campanas y patitas: la ESFERA es la cara, con las agujas corriendo de verdad y el eje del color del jugador. La mitad de abajo se abre para comer.',
      q: 'La alarma: el martillo se dispara entre las dos campanas, el reloj tiembla y el timbrazo sale por los dos lados.',
      muerte: 'Le salta el muelle por arriba, las agujas salen disparadas y se desploma.' },
    { id: 'semaforo', name: 'SEMÁFORO', cat: 'skin',
      ve: 'Las tres luces con su visera, en chapa del color del jugador. La ROJA de arriba hace de ojo —y parpadea— y la VERDE de abajo es la boca.',
      q: 'Se pone en verde: ámbar un instante y sale disparado con rayas de velocidad.',
      muerte: 'Se le funden las tres bombillas de arriba abajo, cada una con su chispazo, y el poste se dobla hasta el suelo.' },
    { id: 'caja', name: 'CAJA FUERTE', cat: 'skin',
      ve: 'Acero remachado con bisagras: la RUEDA de la combinación es el ojo y gira sola. La puerta blindada, con su manilla de oro, es la boca.',
      q: 'Se abre de golpe y escupe monedas por delante.',
      muerte: 'Un reventón le arranca la puerta, que sale por los aires, y se queda vacía con las monedas rodando.' },
    { id: 'bola', name: 'BOLA DE DISCOTECA', cat: 'skin',
      ve: 'Bola de espejos con su enganche arriba: los espejitos se encienden por turnos en los colores del prisma y sueltan haces que barren el laberinto. El bocado de siempre, pero de espejos.',
      q: 'Suelta la pista entera: los haces se disparan, los espejos se encienden todos y la cosa se convierte en una discoteca.',
      muerte: 'Se le van soltando los espejitos uno a uno hasta que lo que queda cae y revienta contra el suelo.',
      ojo: 'La única de la tanda que conserva la silueta: es una bola, y una bola es lo que ya era Pac-Man.' },

    /* --- accesorios --- */
    { id: 'acc_3d', name: 'GAFAS 3D', cat: 'accesorio',
      ve: 'Las de cartón del cine: un cristal rojo, otro cian y la patilla hacia atrás.' },
    { id: 'acc_corona', name: 'CORONA', cat: 'accesorio',
      ve: 'De oro, con tres puntas rematadas en piedra —roja, azul y verde— y el aro con su rubí.' },
    { id: 'acc_boina', name: 'BOINA', cat: 'accesorio',
      ve: 'Boina ladeada del color del jugador, con su cinta y el rabito arriba.' },
    { id: 'acc_monoculo', name: 'MONÓCULO', cat: 'accesorio',
      ve: 'Cristal con aro de oro, ceja de pillo levantada y la cadenita meciéndose al correr.' },
    { id: 'acc_moto', name: 'CASCO DE MOTO', cat: 'accesorio',
      ve: 'Integral, con la visera azulada levantada y una banda del color del jugador cruzándolo.' },
    { id: 'acc_casco', name: 'CASCO DE ASTRONAUTA', cat: 'accesorio', cofre: true,
      ve: 'Burbuja de cristal con el reflejo cruzándola, aro de cuello y una antena con su piloto rojo.' },
    { id: 'acc_cadena', name: 'CADENA DE ORO', cat: 'accesorio', cofre: true,
      ve: 'Los eslabones al cuello y una medalla colgando que se bambolea al correr.' },

    /* --- efectos --- */
    { id: 'efx_burbujas', name: 'BURBUJAS', cat: 'efecto',
      ve: 'Suben burbujas por detrás, cada vez más grandes, hasta que se deshacen.' },
    { id: 'efx_neon', name: 'NEÓN', cat: 'efecto',
      ve: 'Deja un tubo de neón encendido de su color, con su halo, que se va apagando.' },
    { id: 'efx_polaroids', name: 'POLAROIDS', cat: 'efecto',
      ve: 'Va soltando fotos instantáneas que caen girando por el camino.' },
    { id: 'efx_tickets', name: 'TICKETS', cat: 'efecto',
      ve: 'La tira de tickets de premios del salón recreativo, saliendo por detrás.' },
    { id: 'efx_glitch', name: 'GLITCH', cat: 'efecto', cofre: true,
      ve: 'Se descompone en rojo, verde y azul desencajados, con bandas que le cruzan.' },
    { id: 'efx_cinta', name: 'CINTA DE CASETE', cat: 'efecto', cofre: true,
      ve: 'Se le sale la cinta marrón y se va enredando por donde pasa.' },

    /* --- emotes --- */
    { id: 'emo_alucinado', name: 'ALUCINADO', cat: 'emote',
      ve: 'Ojos como platos, cejas por las nubes y la mandíbula por los suelos.' },
    { id: 'emo_pensando', name: 'PENSANDO', cat: 'emote',
      ve: 'Un ojo mirando arriba, el otro entornado, la boca torcida y tres burbujitas que crecen.' },
    { id: 'emo_roto', name: 'CORAZÓN ROTO', cat: 'emote',
      ve: 'Ojos de pena, boca hacia abajo y un corazón que se va partiendo en dos encima.' },
    { id: 'emo_aplauso', name: 'APLAUSO', cat: 'emote',
      ve: 'Dos manos chocando a los lados, ojos contentos y las rayitas del choque.' },
    { id: 'emo_chist', name: 'CHIST', cat: 'emote',
      ve: 'Un ojo guiñado, la boca en O y el dedo cruzado en los labios pidiendo silencio.' }
  ];
